# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(332A2E)
$foreground = rgb(FAE3E9)
$color0 = rgb(594E53)
$color1 = rgb(381428)
$color2 = rgb(202437)
$color3 = rgb(7D354F)
$color4 = rgb(516579)
$color5 = rgb(9C4862)
$color6 = rgb(B5828F)
$color7 = rgb(F0CED6)
$color8 = rgb(A89096)
$color9 = rgb(4B1B35)
$color10 = rgb(2A3049)
$color11 = rgb(A74669)
$color12 = rgb(6C86A1)
$color13 = rgb(D05F82)
$color14 = rgb(F1AEBF)
$color15 = rgb(F0CED6)
