# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(101016)
$foreground = rgb(F6EAF0)
$color0 = rgb(38383E)
$color1 = rgb(453D4F)
$color2 = rgb(493670)
$color3 = rgb(6E5F6F)
$color4 = rgb(AF5180)
$color5 = rgb(AC92A0)
$color6 = rgb(AC92A0)
$color7 = rgb(EAD8E2)
$color8 = rgb(A4979E)
$color9 = rgb(5C5269)
$color10 = rgb(614895)
$color11 = rgb(937E94)
$color12 = rgb(E96CAA)
$color13 = rgb(E6C2D5)
$color14 = rgb(E6C2D5)
$color15 = rgb(EAD8E2)
