palette = "custom"

# base16 template
# [palettes.custom]
# rosewater = "#7DCFFF"
# flamingo = "#C0CAF5"
# pink = "#C0CAF5"
# mauve = "#7DCFFF"
# red = "#414868"
# maroon = "#414868"
# peach = "#F7768E"
# yellow = "#9ECE6A"
# green = "#E0AF68"
# teal = "#7AA2F7"
# sky = "#7AA2F7"
# sapphire = "#BB9AF7"
# blue = "#BB9AF7"
# lavender = "#A9B1D6"
# text = "#C0CAF5"
# subtext1 = "#A9B1D6"
# subtext0 = "#BB9AF7"
# overlay2 = "#7AA2F7"
# overlay1 = "#E0AF68"
# overlay0 = "#9ECE6A"
# surface2 = "#7AA2F7"
# surface1 = "#E0AF68"
# surface0 = "#9ECE6A"
# base = "#1A1B26"
# mantle = "#F7768E"
# crust = "#15161E"

[palettes.custom]
rosewater = "#A9B1D6"
flamingo = "#F7768E"
pink = "#F7768E"
mauve = "#BB9AF7"
red = "#F7768E"
maroon = "#F7768E"
peach = "#E0AF68"
yellow = "#E0AF68"
green = "#9ECE6A"
teal = "#7DCFFF"
sky = "#7DCFFF"
sapphire = "#7AA2F7"
blue = "#7AA2F7"
lavender = "#C0CAF5"
text = "#C0CAF5"
subtext1 = "#C0CAF5"
subtext0 = "#C0CAF5"
overlay2 = "#414868"
overlay1 = "#414868"
overlay0 = "#414868"
surface2 = "#414868"
surface1 = "#414868"
surface0 = "#414868"
base = "#1A1B26"
mantle = "#15161E"
crust = "#15161E"

[character]
success_symbol = '[ ](bold sky)[ ➜](bold green)'
error_symbol = '[ ](bold sky)[ ➜](bold red)'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[custom.todo]
command = "td prompt-today"
when = "td prompt-today | grep -q ."
style = "bold red"
format = "[$output]($style) "
