gui:
  authorColors:
    '*': '#FFFFFF'
  theme:
    activeBorderColor:
      - '#D6ACFF'
    cherryPickedCommitBgColor:
      - '#4D4D4D'
    cherryPickedCommitFgColor:
      - '#D6ACFF'
    defaultFgColor:
      - '#F8F8F2'
    inactiveBorderColor:
      - '#BD93F9'
    optionsTextColor:
      - '#BD93F9'
    searchingActiveBorderColor:
      - '#F1FA8C'
    selectedLineBgColor:
      - '#4D4D4D'
    unstagedChangesColor:
      - '#FF5555'
