gui:
  authorColors:
    '*': '#C0CAF5'
  theme:
    activeBorderColor:
      - '#7AA2F7'
    cherryPickedCommitBgColor:
      - '#414868'
    cherryPickedCommitFgColor:
      - '#7AA2F7'
    defaultFgColor:
      - '#C0CAF5'
    inactiveBorderColor:
      - '#7AA2F7'
    optionsTextColor:
      - '#7AA2F7'
    searchingActiveBorderColor:
      - '#E0AF68'
    selectedLineBgColor:
      - '#414868'
    unstagedChangesColor:
      - '#F7768E'
