version: "3.1"
services:
  reader:
    image: docker.io/hectorqin/reader:latest
    container_name: reader
    restart: always
    ports:
      - 4396:8080
    networks:
      - reader_net
    volumes:
      - ./logs:/logs
      - ./storage:/storage
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50
      - READER_APP_USERBOOKLIMIT=200
      - READER_APP_CACHECHAPTERCONTENT=true
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=123456
    labels:
      - "io.containers.autoupdate=registry"
  # 如果启用远程webview，取消下面注释
  # remote-webview:
  #   image: hectorqin/remote-webview
  #   container_name: remote-webview
  #   restart: always
  #   ports:
  #     - 8050:8050
  #   networks:
  #     - reader_net

networks:
  reader_net:
    driver: bridge
