# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CEDCE9
background         #161517
cursor             #CEDCE9

active_tab_foreground     #161517
active_tab_background     #CEDCE9
inactive_tab_foreground   #CEDCE9
inactive_tab_background   #161517

active_border_color   #CEDCE9
inactive_border_color #161517
bell_border_color     #110E18

color0      #3D3C3F
color1		#110E18
color2		#16151F
color3		#344154
color4		#3B4A6B
color5		#4E6781
color6		#577490
color7		#B1C4D7
color8		#7C8996
color9		#171320
color10		#1D1B2A
color11		#465770
color12		#4F628F
color13		#688AAC
color14		#749BC0
color15		#B1C4D7
