# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6EAF0
background         #101016
cursor             #F6EAF0

active_tab_foreground     #101016
active_tab_background     #F6EAF0
inactive_tab_foreground   #F6EAF0
inactive_tab_background   #101016

active_border_color   #F6EAF0
inactive_border_color #101016
bell_border_color     #453D4F

color0      #38383E
color1		#453D4F
color2		#493670
color3		#6E5F6F
color4		#AF5180
color5		#AC92A0
color6		#AC92A0
color7		#EAD8E2
color8		#A4979E
color9		#5C5269
color10		#614895
color11		#937E94
color12		#E96CAA
color13		#E6C2D5
color14		#E6C2D5
color15		#EAD8E2
