# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAE3E9
background         #332A2E
cursor             #FAE3E9

active_tab_foreground     #332A2E
active_tab_background     #FAE3E9
inactive_tab_foreground   #FAE3E9
inactive_tab_background   #332A2E

active_border_color   #FAE3E9
inactive_border_color #332A2E
bell_border_color     #381428

color0      #594E53
color1		#381428
color2		#202437
color3		#7D354F
color4		#516579
color5		#9C4862
color6		#B5828F
color7		#F0CED6
color8		#A89096
color9		#4B1B35
color10		#2A3049
color11		#A74669
color12		#6C86A1
color13		#D05F82
color14		#F1AEBF
color15		#F0CED6
