# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[properties.wallbash.properties.skip_template]
default = ["waybar.dcol", "waybar.theme", "hypr.theme", "hypr.dcol"]

[properties.hyprland.properties.bar]
default = "hyprpanel"
