services:
  peerbanhelper:
    image: "registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper:latest"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./data:/app/data
    ports:
      - "9898:9898"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8   # Google DNS
      - 114.114.114.114
# 自动更新docker镜像
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    # 环境变量,设置为上海时区
    environment:
        - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8   # Google DNS
      - 114.114.114.114
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: peerbanhelper watchtower --cleanup --schedule "0 0 1 * * *"
