services:
  peerbanhelper:
    image: "registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper:latest"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./data:/app/data
    ports:
      - "9898:9898"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8 # Google DNS
      - 114.114.114.114
    labels:
      - "io.containers.autoupdate=image"
