showonpause=no
seekbarhandlesize=0
showyoutubecomments=yes
updatetitleyoutubestats=yes
showloop=yes
showinfo=yes
# download
downloadpath=Videos/mpv
showyoutubecomments=yes
commentsdownloadpath=Videos/mpv/comments
