rendezvous_server = '192.168.100.109:21116'
nat_type = 2
serial = 0
unlock_pin = ''
trusted_devices = ''

[options]
local-ip-addr = '192.168.2.6'
custom-rendezvous-server = '192.168.100.109'
av1-test = 'Y'
allow-linux-headless = 'Y'
audio-input = 'Built-in Audio Analog Stereo'
key = 'QpA13tn6lV8Qn3xljXs6flffRVjKLjXuVziDQcj5vJQ='
